# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  # runs during prebuild
  - init: |
      pyenv install 3.7.12 
      pyenv local 3.7.12
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
